### ISSUE TITLE
Reserved words

### ISSUE THREAD

**Issue by eksperimental** [marianoguerra/efe#1]
Hi @marianoguerra:
First of all thank you for putting up such a nice project.
I tried to convert Efe to Elixir, and bumped into an issue, which is a function defined with reserved word.
https://github.com/marianoguerra/efe/blob/41d24c47bffc34ca4ab1afe5f36012c574538add/src/efe_var_ann.erl#L62

I solved it by renaming it to "does".
I think it will be wise if the library can error with a message saying it is a reserved word,
and maybe link to https://hexdocs.pm/elixir/syntax-reference.html#reserved-words

Cheers

**Comment by marianoguerra** [comment]
Thanks for the report!
